# .github/workflows/publish.yml
name: Publish VSCode Extension
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g vsce
      - run: vsce publish
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
